### Build
FROM beevelop/ionic:v2021.06.1 AS ionic

## Create app directory
WORKDIR /usr/src/app

## Install app dependencies
## A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
RUN npm install typescript@3.5.3 --save-dev
RUN npm install -f

# ## Set environment variable for openssl legacy support
# ENV NODE_OPTIONS=--openssl-legacy-provider

## Bundle app source
COPY . .
RUN ionic build

### Run
FROM nginx:alpine

## Copy built files to nginx
COPY --from=ionic /usr/src/app/www /usr/share/nginx/html
